### ISSUE TITLE
(optional) integrate Pull Requests with Slack channel

### ISSUE THREAD

**Issue by rladuddlf** [PromoSquad/promotions#61] opened 2021-11-04 15:03 UTC
**As a** ...  developer
**I need** ...  to integrate pull requests with out slack channel
**So that** ...  the channel is notified anytime someone makes a pull request

**Details & Assumptions:** 

**Acceptance Criteria:**

```
Given that I made pull requesets
When I worked on the sprint
Then everyone in the team can be modified by the Slack channel
```

**Comment by dizys** [comment] 2021-11-09 06:09
This is a duplicate of #59

**Closed by dizys** 2021-11-09 06:09 UTC
Labels: enhancement
